services:
  db:
    image: postgres:14.2-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=admin
    ports:
      - "15432:5432"
  web:
    build: ./web/
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: web
    volumes:
      - ./web:/rails
    environment:
      RAILS_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres_volume: 