inherit_from: .rubocop_todo.yml

Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'